name: sistema_alertas
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  geolocator: ^13.0.2 # Para obtener ubicación GPS
  google_maps_flutter: ^2.10.0 # Nuevo paquete para Google Maps
  http: ^1.1.0 # Para realizar solicitudes HTTP

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Para agregar imágenes u otros recursos
  # assets:
  #   - images/mi_imagen.png

  # Para agregar fuentes personalizadas
  # fonts:
  #   - family: MiFuente
  #     fonts:
  #       - asset: fonts/MiFuente-Regular.ttf
